baseURL = 'https://thunderseethe.dev/'
languageCode = 'en-us'
title = "thunderseethe's devlog"
theme = "hugo-coder"
enableEmoji = true
 
[markup.highlight]
style = "github-dark"

[params]
colorScheme = "auto"
hideColorSchemeToggle = false

[taxonomies]
tag = "tags"
seriers = "series"

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

