baseURL = 'https://thunderseethe.dev/'
languageCode = 'en-us'
title = "thunderseethe's devlog"
theme = "hugo-coder"
enableEmoji = true
 
[markup.highlight]
style = "github-dark"

[params]
author = "thunderseethe"
colorScheme = "auto"
hideColorSchemeToggle = false
info = """
Welcome to my blog.


A place to stockpile my musings on whatever catches my fancy.

I'm currently working on [designing a programming language](series/making-a-language)
"""
goatCounter = { code = "thunderseethe" }

[taxonomies]
tag = "tags"
seriers = "series"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/thunderseethe/"

[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"

[[menu.main]]
  name = "Series"
  weight = 2
  url = "series"

